// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"blog/ent/migrate"

	"blog/ent/about"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// About is the client for interacting with the About builders.
	About *AboutClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.About = NewAboutClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		About:  NewAboutClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		About:  NewAboutClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		About.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.About.Use(hooks...)
}

// AboutClient is a client for the About schema.
type AboutClient struct {
	config
}

// NewAboutClient returns a client for the About from the given config.
func NewAboutClient(c config) *AboutClient {
	return &AboutClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `about.Hooks(f(g(h())))`.
func (c *AboutClient) Use(hooks ...Hook) {
	c.hooks.About = append(c.hooks.About, hooks...)
}

// Create returns a builder for creating a About entity.
func (c *AboutClient) Create() *AboutCreate {
	mutation := newAboutMutation(c.config, OpCreate)
	return &AboutCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of About entities.
func (c *AboutClient) CreateBulk(builders ...*AboutCreate) *AboutCreateBulk {
	return &AboutCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for About.
func (c *AboutClient) Update() *AboutUpdate {
	mutation := newAboutMutation(c.config, OpUpdate)
	return &AboutUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AboutClient) UpdateOne(a *About) *AboutUpdateOne {
	mutation := newAboutMutation(c.config, OpUpdateOne, withAbout(a))
	return &AboutUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AboutClient) UpdateOneID(id int) *AboutUpdateOne {
	mutation := newAboutMutation(c.config, OpUpdateOne, withAboutID(id))
	return &AboutUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for About.
func (c *AboutClient) Delete() *AboutDelete {
	mutation := newAboutMutation(c.config, OpDelete)
	return &AboutDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AboutClient) DeleteOne(a *About) *AboutDeleteOne {
	return c.DeleteOneID(a.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *AboutClient) DeleteOneID(id int) *AboutDeleteOne {
	builder := c.Delete().Where(about.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AboutDeleteOne{builder}
}

// Query returns a query builder for About.
func (c *AboutClient) Query() *AboutQuery {
	return &AboutQuery{
		config: c.config,
	}
}

// Get returns a About entity by its id.
func (c *AboutClient) Get(ctx context.Context, id int) (*About, error) {
	return c.Query().Where(about.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AboutClient) GetX(ctx context.Context, id int) *About {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AboutClient) Hooks() []Hook {
	return c.hooks.About
}
