// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog/ent/about"
	"blog/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	aboutFields := schema.About{}.Fields()
	_ = aboutFields
	// aboutDescTitle is the schema descriptor for title field.
	aboutDescTitle := aboutFields[0].Descriptor()
	// about.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	about.TitleValidator = aboutDescTitle.Validators[0].(func(string) error)
}
