// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AboutsColumns holds the columns for the "abouts" table.
	AboutsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Nullable: true},
	}
	// AboutsTable holds the schema information for the "abouts" table.
	AboutsTable = &schema.Table{
		Name:       "abouts",
		Columns:    AboutsColumns,
		PrimaryKey: []*schema.Column{AboutsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AboutsTable,
	}
)

func init() {
}
